import type { IApiService } from '@/services/IApiService'
import { readonly, ref } from 'vue'
import { appStore } from '@/stores/appStorage'
import type { PayfortFormInput } from '@/gql/graphql'

/**
 * A composable that encapsulates the logic for initiating the checkout process
 * by fetching the Payfort payment form from the backend.
 *
 * @param apiService An instance of the ApiService.
 * @returns An object with reactive state and methods to manage the checkout flow.
 */
export const useCheckout = (apiService: IApiService) => {
  // --- Reactive State ---

  /**
   * Indicates if a checkout operation is currently in progress.
   */
  const isLoading = ref<boolean>(false)

  /**
   * Holds any error that occurred during the checkout process.
   * It's null if there is no error.
   */
  const error = ref<Error | null>(null)

  /**
   * Stores the raw HTML of the Payfort form returned from the API.
   */
  const payfortFormHtml = ref('')

  // --- Methods ---

  /**
   * The main method to start the payment process. It orchestrates the API calls
   * to generate a merchant reference and then the Payfort form.
   * It manages the internal loading and error states.
   *
   * @param deviceFingerprint The session ID generated by the Snare.js script.
   * @param options Additional options for the payment, like whether to save the card.
   */
  async function initiatePayment(
    deviceFingerprint: string,
    options: { saveCard: boolean } = { saveCard: false }
  ): Promise<void> {
    // 1. Set loading state and clear previous errors/data.
    isLoading.value = true
    error.value = null
    payfortFormHtml.value = ''

    try {
      // 2. Generate a unique reference for this transaction.
      const merchantRef = await apiService.generateMerchantReference(appStore().site)

      const formInput: PayfortFormInput = {
        merchantReference: merchantRef,
        deviceFingerprint,
        savePaymentCard: options.saveCard
      }

      // 3. Generate the final Payfort form HTML.
      const formHtml = await apiService.generatePayfortForm(appStore().site, formInput)

      // 4. On success, update the state with the form HTML.
      payfortFormHtml.value = formHtml
    } catch (e) {
      // 5. If any step fails, capture the error and expose it in the state.
      const caughtError = e instanceof Error ? e : new Error('An unknown checkout error occurred')
      error.value = caughtError
      console.error('Failed to initiate payment:', caughtError)
    } finally {
      // 6. Always set loading to false when the operation is complete.
      isLoading.value = false
    }
  }

  return {
    // --- Exposed State (Read-only) ---
    // The component can read this state but cannot modify it directly.
    isLoading: readonly(isLoading),
    error: readonly(error),
    payfortFormHtml: readonly(payfortFormHtml),

    // --- Exposed Methods (Actions) ---
    // This is the only way for the component to trigger changes.
    initiatePayment
  }
}
