import { readonly, ref } from 'vue'
import { useShopApiService } from '@/modules/shop/composables/useShopApiService'

export interface PaymentLinkBuyer {
  paymentLinkId: string
  fullName: string
  email: string
  mobilePhone: string
}

/**
 * Encapsulates the anonymous payment-link card checkout: it creates the payment-link transaction
 * (persisting the buyer's name/email/mobile phone) and then fetches the signed Payfort card form.
 */
export const usePaymentLinkCheckout = () => {
  const shopApi = useShopApiService()

  const isLoading = ref<boolean>(false)
  const error = ref<Error | null>(null)
  const payfortFormHtml = ref('')

  /**
   * Creates the payment-link transaction and generates the Payfort card form HTML.
   *
   * @param buyer The buyer details (name/email/mobile phone) and payment link id.
   * @param deviceFingerprint The session ID generated by the Snare.js script.
   */
  async function initiatePayment(buyer: PaymentLinkBuyer, deviceFingerprint: string): Promise<void> {
    isLoading.value = true
    error.value = null
    payfortFormHtml.value = ''

    try {
      const { merchantReference } = await shopApi.createPaymentLinkTransaction({
        paymentLinkId: buyer.paymentLinkId,
        fullName: buyer.fullName,
        email: buyer.email,
        mobilePhone: buyer.mobilePhone
      })

      payfortFormHtml.value = await shopApi.generatePaymentLinkPayfortForm({
        merchantReference,
        deviceFingerprint
      })
    } catch (e) {
      const caughtError = e instanceof Error ? e : new Error('An unknown checkout error occurred')
      error.value = caughtError
      console.error('Failed to initiate payment link payment:', caughtError)
    } finally {
      isLoading.value = false
    }
  }

  return {
    isLoading: readonly(isLoading),
    error: readonly(error),
    payfortFormHtml: readonly(payfortFormHtml),
    initiatePayment
  }
}
