fragment ShoppingCartFields on ShoppingCart {
  id
  currency
  discountCode
  giftCardsCodes
  total {
    __typename
    ... on ShoppingCartTotal {
      total
      subTotal
      giftCardAmount
      amountToPay
    }
    ... on GiftCardIsNotUsable {
      code
    }
    ... on UserCanNotBuyFirstTimerPackage {
      code
    }
    ... on UserAlreadyHaveFirstTimerPackage {
      code
    }
  }
  items {
    id
    quantity
    subtotal
    variant {
      id
      name
      position
      price
      product {
        ...ProductBasicFields
      }
    }
  }
}
